"""Added profile_photo field to User model

Revision ID: 08b9e66327e4
Revises: 
Create Date: 2025-04-10 19:47:32.678047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b9e66327e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pin_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gst_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('gst_number')
        batch_op.drop_column('logo')
        batch_op.drop_column('pin_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
